#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Enable SPI & UART in armbianEnv #
########################################
echo "overlays=uart3 spi-spidev" >> "${ARMBIAN_CONFIG_TXT_FILE}"

# Disable OTG serial console

if [[ ! -d /etc/modprobe.d ]]; then
    mkdir -p /etc/modprobe.d
fi
if [[ -d /etc/modprobe.d ]]; then
    echo "blacklist serial_g" >> /etc/modprobe.d/blacklist.conf
fi

########################################
# Fix pillow version to 9.5 for bananapi
########################################
mkdir -p "/home/${BASE_USER}/.config/pip"
echo "pillow==9.5.0" > "/home/${BASE_USER}/.config/pip/constraints.txt"
cat > "/home/${BASE_USER}/.config/pip/pip.conf" <<EOF
[global]
constraint = /home/${BASE_USER}/.config/pip/constraints.txt
EOF