#### Configure workflow matrix
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/MSzturc/THEOS
####
#### This File is distributed under GPLv3
####

#### NOTE: Use entries according to their directory/file structure in 'config'
####       e.g. raspberry/rpi32 armbian/orangepi3lts ...

# Use this categorie to configure behaviour on pushes/pull requests against
# develop branch
# Each entry will be used in setup matrix

buildtest:
  - armbian/bananapim2zero
  - armbian/bananapim2zero_nightly
  - armbian/orangepi_zero3
  - armbian/orangepi_zero3_nightly

# This is used to setup release build chain.
# Each entry will be used in setup matrix for releases

release:
  - armbian/bananapim2zero
  - armbian/orangepi_zero3
