- name: banana_pi_m2_zero-bookworm
  type: armbian
  img_download_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-bananapi_m2_zero_bookworm.img.xz"
  img_hash_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-bananapi_m2_zero_bookworm.img.xz.sha256"
  env:
    ARCH: armhf
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 20-bpi-m2zero
  rpi_json:
    name: "THEOS $VERSION$ - Banana Pi M2 Zero"
    description: "A prebuilt Image for Banana Pi M2 Zero with preinstalled Klipper, Moonraker, and Mainsail — optimized for running the T100 and T250 3D printers."
    icon: "https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
    init_format: "systemd"
    devices:
      - "bananapim2zero-32bit"

- name: banana_pi_m2_zero-trixie
  type: armbian
  img_download_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-bananapi_m2_zero_trixie.img.xz"
  img_hash_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-bananapi_m2_zero_trixie.img.xz.sha256"
  env:
    ARCH: armhf
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 20-bpi-m2zero
  rpi_json:
    name: "THEOS $VERSION$ - Banana Pi M2 Zero"
    description: "A prebuilt Image for Banana Pi M2 Zero with preinstalled Klipper, Moonraker, and Mainsail — optimized for running the T100 and T250 3D printers."
    icon: "https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
    init_format: "systemd"
    devices:
      - "bananapim2zero-32bit"

- name: armbian-orangepi_zero3-bookworm
  type: armbian
  img_download_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-orangepi_zero3_bookworm.img.xz"
  img_hash_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-orangepi_zero3_bookworm.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 20-opi-zero3
  rpi_json:
    name: "THEOS $VERSION$ - Orange Pi Zero3"
    description: "A prebuilt Image for Orange Pi Zero3 with preinstalled Klipper, Moonraker, and Mainsail — optimized for running the T100 and T250 3D printers."
    icon: "https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
    init_format: "systemd"
    devices:
      - "orangepizero3-64bit"

- name: armbian-orangepi_zero3-trixie
  type: armbian
  img_download_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-orangepi_zero3_trixie.img.xz"
  img_hash_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-orangepi_zero3_trixie.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 20-opi-zero3
  rpi_json:
    name: "THEOS $VERSION$ - Orange Pi Zero3"
    description: "A prebuilt Image for Orange Pi Zero3 with preinstalled Klipper, Moonraker, and Mainsail — optimized for running the T100 and T250 3D printers."
    icon: "https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
    init_format: "systemd"
    devices:
      - "orangepizero3-64bit"

- name: armbian-radxa_cubie_a5e-bookworm
  type: armbian
  img_download_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-radxa_cubie_a5e_bookworm.img.xz"
  img_hash_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-radxa_cubie_a5e_bookworm.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules: []
  rpi_json:
    name: "THEOS $VERSION$ - Radxa Cubie A5E"
    description: "A prebuilt Image for Radxa Cubie A5E with preinstalled Klipper, Moonraker, and Mainsail — optimized for running the T100 and T250 3D printers."
    icon: "https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
    init_format: "systemd"
    devices:
      - "radxa-cubie-a5e-64bit"

- name: armbian-radxa_cubie_a5e-trixie
  type: armbian
  img_download_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-radxa_cubie_a5e_trixie.img.xz"
  img_hash_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-radxa_cubie_a5e_trixie.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules: []
  rpi_json:
    name: "THEOS $VERSION$ - Radxa Cubie A5E"
    description: "A prebuilt Image for Radxa Cubie A5E with preinstalled Klipper, Moonraker, and Mainsail — optimized for running the T100 and T250 3D printers."
    icon: "https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
    init_format: "systemd"
    devices:
      - "radxa-cubie-a5e-64bit"

- name: armbian-radxa_dragon_q6a-trixie
  type: armbian
  img_download_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-radxa_dragon_q6a_trixie.img.xz"
  img_hash_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-radxa_dragon_q6a_trixie.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
    ROOT_PARTITION: 3
    WINDOWS_CONFIG_PARTITION: 1
  special_modules: []
  rpi_json:
    name: "THEOS $VERSION$ - Radxa Dragon Q6A"
    description: "A prebuilt Image for Radxa Dragon Q6A with preinstalled Klipper, Moonraker, and Mainsail — optimized for running the T100 and T250 3D printers."
    icon: "https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
    init_format: "systemd"
    devices:
      - "radxa-dragon-q6a-64bit"

- name: armbian-rpi_5-bookworm
  type: armbian
  img_download_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-rpi_5_bookworm.img.xz"
  img_hash_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-rpi_5_bookworm.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules: []
  rpi_json:
    name: "THEOS $VERSION$ - Raspberry PI5"
    description: "A prebuilt Image for Raspberry PI5 with preinstalled Klipper, Moonraker, and Mainsail — optimized for running the T100 and T250 3D printers."
    icon: "https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
    init_format: "systemd"
    devices:
      - "rpi5-64bit"

- name: armbian-rpi_5-trixie
  type: armbian
  img_download_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-rpi_5_trixie.img.xz"
  img_hash_url: "https://github.com/MSzturc/armbian-builds/releases/latest/download/armbian-rpi_5_trixie.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 6000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules: []
  rpi_json:
    name: "THEOS $VERSION$ - Raspberry PI5"
    description: "A prebuilt Image for Raspberry PI5 with preinstalled Klipper, Moonraker, and Mainsail — optimized for running the T100 and T250 3D printers."
    icon: "https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
    init_format: "systemd"
    devices:
      - "rpi5-64bit"